performance_thresholds:
  target_roas: 3.0
  min_acceptable_roas: 1.5
  high_performer_roas: 4.0
  target_acos: 33.3  # 1/3 = 33.3%
  
click_thresholds:
  min_clicks_for_analysis: 10
  zero_conversion_click_threshold: 50
  pause_after_clicks: 100
  
ctr_thresholds:
  min_acceptable_ctr: 0.5
  good_ctr: 1.5
  excellent_ctr: 3.0
  
conversion_thresholds:
  min_acceptable_cr: 0.5
  good_cr: 2.0
  excellent_cr: 4.0
  
spend_thresholds:
  min_spend_for_analysis: 10.0
  daily_budget_min: 10.0
  daily_budget_max: 1000.0
  
volume_thresholds:
  min_impressions_for_keyword: 50
  min_impressions_for_negative: 1000
  high_volume_percentile: 70
  
bid_adjustment_limits:
  max_bid_increase_percent: 30
  max_bid_decrease_percent: 30
  min_bid: 0.50
  max_bid: 10.00
  
budget_adjustment_limits:
  max_budget_increase_factor: 1.5
  max_budget_decrease_factor: 0.5
  pause_budget_threshold: 0.0
  
opportunity_scoring:
  impression_weight: 0.3
  roas_weight: 0.4
  supplier_share_weight: 0.3
  
confidence_scores:
  high_confidence: 0.9
  medium_confidence: 0.7
  low_confidence: 0.5